name: prajna_admin
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.12.9+2
  fluttertoast: ^3.1.2
  image_picker: ^0.6.1+4
  shared_preferences: 0.5.3+4
  firebase_storage: 3.0.3
  cached_network_image: ^1.1.1
  intl: ^0.16.0
  firebase_messaging: ^5.1.4
  flutter_local_notifications: ^0.8.2
  photo_view: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - images/img_not_available.jpeg
     - images/mimi1.gif
     - images/mimi2.gif
     - images/mimi3.gif
     - images/mimi4.gif
     - images/mimi5.gif
     - images/mimi6.gif
     - images/mimi7.gif
     - images/mimi8.gif
     - images/mimi9.gif
